/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marks.view;

import javax.swing.JOptionPane;

import marks.presenter.StudentPresenter;
import marks.presenter.IndexedStudent;
import marks.model.Student;

/**
 *
 * @author chamari
 */
public class StudentView extends javax.swing.JFrame implements IView<IndexedStudent> {

    // the presenter for this view
    private StudentPresenter presenter;

    /**
     * Creates new form StudentView
     */
    public StudentView(StudentPresenter sp) {
        presenter = sp;
        // create GUI
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabelResutsTopic = new javax.swing.JLabel();
        jLableStudentDetailsTopic = new javax.swing.JLabel();
        jLableStudentID = new javax.swing.JLabel();
        jLableAssignment1 = new javax.swing.JLabel();
        jLableAssignment2 = new javax.swing.JLabel();
        jLableExamMarks = new javax.swing.JLabel();
        jLableTotalMarks = new javax.swing.JLabel();
        jLableGrade = new javax.swing.JLabel();
        textFieldStudentID = new javax.swing.JTextField();
        textFieldAssignment1 = new javax.swing.JTextField();
        textFieldAssignment2 = new javax.swing.JTextField();
        textFieldExam = new javax.swing.JTextField();
        textFieldTotal = new javax.swing.JTextField();
        textFieldGrade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaResult = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jBtnPreviouse = new javax.swing.JButton();
        jBtnNext = new javax.swing.JButton();
        jTFIndex = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFMax = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelSID = new javax.swing.JLabel();
        jTFCalculateGradeSID = new javax.swing.JTextField();
        jBtnCalculateGrade = new javax.swing.JButton();
        jBtnCalculateGradeAllStudents = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelTolerance = new javax.swing.JLabel();
        jBtnFindBorderline = new javax.swing.JButton();
        jBtnAllStudentinBorderline1 = new javax.swing.JButton();
        jLabelTolerance1 = new javax.swing.JLabel();
        jTFTolerance = new javax.swing.JTextField();
        textAreaMinValue = new javax.swing.JTextField();
        textAreaMaxValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jBtnUpdateStudentRecords = new javax.swing.JButton();
        jLabelUpdateRecordsStudentID = new javax.swing.JLabel();
        jTFUpdateRecordsStudentID = new javax.swing.JTextField();
        jBtnSearchStudent = new javax.swing.JButton();
        SelectAll = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        textFieldSearchStudentByGrade = new javax.swing.JTextField();
        searchStudents = new javax.swing.JButton();
        grade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marks Management System");

        jLabelResutsTopic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelResutsTopic.setText("Results");

        jLableStudentDetailsTopic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLableStudentDetailsTopic.setText("Student Details");

        jLableStudentID.setFont(new java.awt.Font("Cambria Math", 0, 13)); // NOI18N
        jLableStudentID.setText("Student ID");

        jLableAssignment1.setFont(new java.awt.Font("Cambria Math", 0, 13)); // NOI18N
        jLableAssignment1.setText("Assignment 1");

        jLableAssignment2.setFont(new java.awt.Font("Cambria Math", 0, 13)); // NOI18N
        jLableAssignment2.setText("Assignment 2");

        jLableExamMarks.setFont(new java.awt.Font("Cambria Math", 0, 13)); // NOI18N
        jLableExamMarks.setText("Exam Marks");

        jLableTotalMarks.setFont(new java.awt.Font("Cambria Math", 0, 13)); // NOI18N
        jLableTotalMarks.setText("Total Marks");

        jLableGrade.setFont(new java.awt.Font("Cambria Math", 0, 13)); // NOI18N
        jLableGrade.setText("Grade");

        textFieldAssignment1.setToolTipText("");

        textFieldTotal.setEditable(false);

        textFieldGrade.setEditable(false);
        textFieldGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldGradeActionPerformed(evt);
            }
        });

        textAreaResult.setEditable(false);
        textAreaResult.setColumns(20);
        textAreaResult.setRows(5);
        jScrollPane1.setViewportView(textAreaResult);

        jBtnPreviouse.setText("Previouse");
        jBtnPreviouse.setEnabled(false);
        jBtnPreviouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPreviouseActionPerformed(evt);
            }
        });

        jBtnNext.setText("Next");
        jBtnNext.setEnabled(false);
        jBtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNextActionPerformed(evt);
            }
        });

        jLabel1.setText("Of");

        jTFMax.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculate Grade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 11))); // NOI18N

        jLabelSID.setText("Student ID");

        jBtnCalculateGrade.setText("Calculate Grade");
        jBtnCalculateGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalculateGradeActionPerformed(evt);
            }
        });

        jBtnCalculateGradeAllStudents.setText("Calculate Grade All Students");
        jBtnCalculateGradeAllStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalculateGradeAllStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCalculateGradeSID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnCalculateGrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCalculateGradeAllStudents)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSID)
                    .addComponent(jTFCalculateGradeSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCalculateGrade)
                    .addComponent(jBtnCalculateGradeAllStudents))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Find Borderline", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 11))); // NOI18N

        jLabelTolerance.setText("Tolerance");

        jBtnFindBorderline.setText("Find Borderline");
        jBtnFindBorderline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFindBorderlineActionPerformed(evt);
            }
        });

        jBtnAllStudentinBorderline1.setText("Find Range");
        jBtnAllStudentinBorderline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAllStudentinBorderline1ActionPerformed(evt);
            }
        });

        jLabelTolerance1.setText("Range");

        textAreaMinValue.setToolTipText("");
        textAreaMinValue.setName("MIN"); // NOI18N
        textAreaMinValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAreaMinValueActionPerformed(evt);
            }
        });

        textAreaMaxValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAreaMaxValueActionPerformed(evt);
            }
        });

        jLabel2.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTolerance1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textAreaMinValue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAreaMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAllStudentinBorderline1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnFindBorderline, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnFindBorderline)
                    .addComponent(jTFTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAllStudentinBorderline1)
                    .addComponent(jLabelTolerance1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAreaMinValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAreaMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textAreaMinValue.getAccessibleContext().setAccessibleName("");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Student Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 11))); // NOI18N

        jBtnUpdateStudentRecords.setText("Update Student Records");
        jBtnUpdateStudentRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateStudentRecordsActionPerformed(evt);
            }
        });

        jLabelUpdateRecordsStudentID.setText("Student ID");

        jBtnSearchStudent.setText("Search Student");
        jBtnSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUpdateRecordsStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFUpdateRecordsStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnSearchStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnUpdateStudentRecords)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelUpdateRecordsStudentID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFUpdateRecordsStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnSearchStudent))
                    .addComponent(jBtnUpdateStudentRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        SelectAll.setText("Browse All Student");
        SelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectAllActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Students by Grade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 11))); // NOI18N

        searchStudents.setText("Find Students by Grade ");
        searchStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentsActionPerformed(evt);
            }
        });

        grade.setText("Grade");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldSearchStudentByGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchStudents)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grade)
                    .addComponent(textFieldSearchStudentByGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStudents))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jBtnPreviouse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFMax, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnNext)
                        .addGap(32, 32, 32)
                        .addComponent(SelectAll)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLableStudentDetailsTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLableTotalMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLableGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLableStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(textFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLableAssignment1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(textFieldAssignment1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLableExamMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldExam, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLableAssignment2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldAssignment2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelResutsTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 19, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnPreviouse)
                    .addComponent(jTFIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNext)
                    .addComponent(SelectAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResutsTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLableStudentDetailsTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLableStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLableAssignment1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldAssignment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLableAssignment2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldAssignment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLableExamMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLableTotalMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLableGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCalculateGradeAllStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalculateGradeAllStudentsActionPerformed

        textAreaResult.setText(" ");//clear teaxt area
        presenter.calculateGradeAllStudent();
    }//GEN-LAST:event_jBtnCalculateGradeAllStudentsActionPerformed
    // handles call when Calculate Grade Button is clicked
    private void jBtnCalculateGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalculateGradeActionPerformed

        textAreaResult.setText(" ");//clear teaxt area
        presenter.selectByStudentIDCalculateGrade(jTFCalculateGradeSID.getText());

    }//GEN-LAST:event_jBtnCalculateGradeActionPerformed

    private void jBtnUpdateStudentRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateStudentRecordsActionPerformed

        textAreaResult.setText(" ");//clear teaxt area

        presenter.updateStudent(textFieldStudentID.getText(), textFieldAssignment1.getText(), textFieldAssignment2.getText(), textFieldExam.getText(), textFieldTotal.getText(), textFieldGrade.getText());


    }//GEN-LAST:event_jBtnUpdateStudentRecordsActionPerformed
    // handles call when Find Borderline Button is clicked
    private void jBtnFindBorderlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFindBorderlineActionPerformed

        textAreaResult.setText(" ");//clear teaxt area
        presenter.selectByTolerance(jTFTolerance.getText());
    }//GEN-LAST:event_jBtnFindBorderlineActionPerformed
    // handles call when previousButton is clicked
    private void jBtnPreviouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPreviouseActionPerformed

        presenter.showPrevious();
    }//GEN-LAST:event_jBtnPreviouseActionPerformed
    // handles call when nextButton is clicked
    private void jBtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNextActionPerformed

        presenter.showNext();

    }//GEN-LAST:event_jBtnNextActionPerformed
    // handles call when Find Range Button is clicked
    private void jBtnAllStudentinBorderline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAllStudentinBorderline1ActionPerformed

        textAreaResult.setText(" ");//clear teaxt area
        presenter.selectByFindRange(textAreaMinValue.getText(), textAreaMaxValue.getText());
    }//GEN-LAST:event_jBtnAllStudentinBorderline1ActionPerformed
    // handles call when Search Student Button is clicked
    private void jBtnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchStudentActionPerformed

        textAreaResult.setText("");//clear teaxt area
        presenter.selectByStudentIDSearchStudent(jTFUpdateRecordsStudentID.getText());

    }//GEN-LAST:event_jBtnSearchStudentActionPerformed

    private void SelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectAllActionPerformed

        textAreaResult.setText("");//clear teaxt area
        presenter.selectAll();
    }//GEN-LAST:event_SelectAllActionPerformed

    private void textFieldGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldGradeActionPerformed

    private void searchStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentsActionPerformed

        textAreaResult.setText("");//clear teaxt area
        presenter.searchStudentByGrade(textFieldSearchStudentByGrade.getText());
    }//GEN-LAST:event_searchStudentsActionPerformed

    private void textAreaMinValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAreaMinValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAreaMinValueActionPerformed

    private void textAreaMaxValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAreaMaxValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAreaMaxValueActionPerformed

// GUI components
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SelectAll;
    private javax.swing.JLabel grade;
    private javax.swing.JButton jBtnAllStudentinBorderline1;
    private javax.swing.JButton jBtnCalculateGrade;
    private javax.swing.JButton jBtnCalculateGradeAllStudents;
    private javax.swing.JButton jBtnFindBorderline;
    private javax.swing.JButton jBtnNext;
    private javax.swing.JButton jBtnPreviouse;
    private javax.swing.JButton jBtnSearchStudent;
    private javax.swing.JButton jBtnUpdateStudentRecords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelResutsTopic;
    private javax.swing.JLabel jLabelSID;
    private javax.swing.JLabel jLabelTolerance;
    private javax.swing.JLabel jLabelTolerance1;
    private javax.swing.JLabel jLabelUpdateRecordsStudentID;
    private javax.swing.JLabel jLableAssignment1;
    private javax.swing.JLabel jLableAssignment2;
    private javax.swing.JLabel jLableExamMarks;
    private javax.swing.JLabel jLableGrade;
    private javax.swing.JLabel jLableStudentDetailsTopic;
    private javax.swing.JLabel jLableStudentID;
    private javax.swing.JLabel jLableTotalMarks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTFCalculateGradeSID;
    private javax.swing.JTextField jTFIndex;
    private javax.swing.JTextField jTFMax;
    private javax.swing.JTextField jTFTolerance;
    private javax.swing.JTextField jTFUpdateRecordsStudentID;
    private javax.swing.JButton searchStudents;
    private javax.swing.JTextField textAreaMaxValue;
    private javax.swing.JTextField textAreaMinValue;
    private javax.swing.JTextArea textAreaResult;
    private javax.swing.JTextField textFieldAssignment1;
    private javax.swing.JTextField textFieldAssignment2;
    private javax.swing.JTextField textFieldExam;
    private javax.swing.JTextField textFieldGrade;
    private javax.swing.JTextField textFieldSearchStudentByGrade;
    private javax.swing.JTextField textFieldStudentID;
    private javax.swing.JTextField textFieldTotal;
    // End of variables declaration//GEN-END:variables

    // IView interface implementation
    @Override
    public void displayRecord(IndexedStudent iStudent) {
        Student student = iStudent.getStudent();
        textFieldStudentID.setText(student.getId());
        textFieldAssignment1.setText(Integer.toString(student.getAssignment1()));
        textFieldAssignment2.setText(Integer.toString(student.getAssignment2()));
        textFieldExam.setText(Integer.toString(student.getExamMarks()));
        textFieldTotal.setText(Integer.toString(student.getTotalMarks()));
        textFieldGrade.setText(student.getGrade());

        jTFMax.setText(Integer.toString(iStudent.getSize()));
        jTFIndex.setText(Integer.toString(iStudent.getIndex()));
    }

    @Override
    public void displayMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Message", JOptionPane.PLAIN_MESSAGE);
    }

    @Override
    public void setBrowsing(boolean flag) {

        jBtnNext.setEnabled(flag);
        jBtnPreviouse.setEnabled(flag);
    }

    @Override
    public void displayError(String error) {
        System.err.println(error);
    }

    @Override
    public void displayRecordTxt(IndexedStudent iStudent) {
        Student student = iStudent.getStudent();
        textAreaResult.append(student.getId() + "," + student.getAssignment1() + "," + student.getAssignment2() + "," + student.getExamMarks() + "," + student.getTotalMarks() + "," + student.getGrade() + "," + "\n");
    }
}
